default:
    tags: 
        - python

variables:
    IMAGE_NAME: vedant551/demo-app
    IMAGE_TAG: python-app-1.0

run_tests:
    image: python:3.9-slim-buster
    before_script:
        - apt-get update && apt-get install make && apt-get install -y gcc python3-dev
    script: 
        - make test
    only:
        - tags
        - master
        - main
        - merge_requests

build_image:
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"  
    before_script:
        - docker login -u $REGISTRY_USER --password $REGISTRY_PASS
    script:
        - docker build . --file build/Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
        - docker push $IMAGE_NAME:$IMAGE_TAG
    only:
        - tags
        - master
        - main
        - merge_requests
