default:
    tags: 
        - python

run_tests:
    image: python:3.9-slim-buster
    before_script:
        - apt-get update && apt-get install make && apt-get install gcc python3-dev
    script: 
        - make test
